FROM debian:stable-20190610-slim

RUN apt-get update

RUN apt-get install -yq --no-install-recommends --no-install-suggests apt-utils

RUN apt-get install -yq --no-install-recommends --no-install-suggests \
    pdns-server pdns-backend-remote
