cc_library(
    name = "options",
    hdrs = ["options.hpp"],
    deps = [
      "//dometer/dns/resolver:options",
      "//dometer/dns/server:options",
    ],
    visibility = ["//visibility:public"],
)
