cc_library(
    name = "options",
    hdrs = ["options.hpp"],
    deps = [
        "//dometer/app/dns:options",
        "//dometer/app/metrics:options",
    ],
    visibility = ["//visibility:public"],
)
