cc_library(
    name = "prometheus",
    hdrs = ["prometheus.hpp"],
    deps = [
        "//dometer/config/metrics/handler/prometheus/transport:transport"
    ],
    visibility = ["//visibility:public"],
)


