cc_library(
    name = "callback",
    hdrs = ["callback.hpp"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "emitter",
    hdrs = ["emitter.hpp", "emitter.ipp"],
    deps = [
        ":callback"
    ],
    visibility = ["//visibility:public"],
)
