cc_library(
    name = "expected",
    hdrs = ["expected.hpp"],
    deps = ["@com_github_TartanLlama_expected//:expected"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "optional",
    hdrs = ["optional.hpp"],
    deps = ["@com_github_TartanLlama_optional//:optional"],
    visibility = ["//visibility:public"],
)
