cc_library(
    name = "json_serde",
    hdrs = ["json_serde.h"],
    srcs = ["json_serde.cc"],
    deps = [
        "@jsoncpp//:jsoncpp",
        "//std/experimental:expected",
    ],
    visibility = ["//visibility:public"],
)
