cc_library(
    name = "validator",
    deps = [
        "@com_github_Tencent_rapidjson//:rapidjson",
    ],
    hdrs = ["validator.hpp"],
    srcs = ["validator.cpp"],
    visibility = ["//visibility:public"],
)
