cc_library(
    name = "parser",
    hdrs = ["parser.hpp"],
    srcs = ["parser.cpp"],
    deps = [
      "//dometer/dns:options",
      "//dometer/config/dns/resolver:parser",
      "//dometer/config/dns/server:parser",
    ],
    visibility = ["//visibility:public"],
)
