cc_library(
    name = "dns_parser",
    hdrs = ["dns_parser.hpp"],
    srcs = ["dns_parser.cpp"],
    deps = [
      "//dometer/app/dns:options",
      "//dometer/config/dns/resolver:resolver_parser",
      "//dometer/config/dns/server:server_parser",
    ],
    visibility = ["//visibility:public"],
)
