cc_library(
    name = "socket_factory",
    hdrs = ["socket_factory.h"],
    deps = ["//std/experimental:expected", "//util/error:system_exception"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "unix_socket",
    hdrs = ["unix_socket.h"],
    deps = ["//std/experimental:expected", "//util/error:system_exception"],
    visibility = ["//visibility:public"],
)
