cc_library(
  name = "unix_socket_remote_backend",
  hdrs = ["unix_socket_remote_backend.h"],
  srcs = ["unix_socket_remote_backend.cc"],
  deps = [
      "//network/socket:socket_factory",
      "//network/socket:unix_socket",
      "//std/experimental:expected",
      "//util:json_serde",
  ],
  visibility = ["//visibility:public"],
)
