cc_library(
  name = "unix_socket_backend",
  hdrs = ["unix_socket_backend.h"],
  srcs = ["unix_socket_backend.cc"],
  deps = ["//std/experimental:expected", "//util:readline"],
  visibility = ["//visibility:public"],
)
