cc_library(
    name = "class",
    hdrs = ["class.hpp"],
    srcs = ["class.cpp"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "record",
    hdrs = ["record.hpp"],
    deps = [
        ":type",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "type",
    hdrs = ["type.hpp"],
    srcs = ["type.cpp"],
    visibility = ["//visibility:public"],
)
