cc_library(
    name = "types",
    deps = [
        "@com_github_jupp0r_prometheus_cpp//core",
        "@com_github_jupp0r_prometheus_cpp//pull",
        "@com_github_jupp0r_prometheus_cpp//push",
    ],
    hdrs = [
        "types.hpp",
    ],
    srcs = [],
    visibility = ["//visibility:public"],
)
