name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest]
        include:
          - platform: macos-latest
            os: darwin
          - platform: ubuntu-latest
            os: linux
    runs-on: ${{ matrix.platform }}    
    steps:
      - id: add-github-workspace-bin-to-path
        name: Add ${GITHUB_WORKSPACE}/bin to path
        run: |
          echo "::add-path::/${GITHUB_WORKSPACE}/bin"
      - id: checkout
        name: Checkout
        uses: actions/checkout@v1
      - id: check_bazel
        name: Check for Bazel
        continue-on-error: true
        run: |
          bazel version
      - id: check_cmake
        name: Check for CMake
        continue-on-error: false
        run: |
          cmake --version
      - id: download_bazel
        name: Download Bazel(isk)
        if: steps.check_bazel.outcome == "failure"
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.4.0/bazelisk-${{ matrix.os }}-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-${{ matrix.os }}-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
          "${GITHUB_WORKSPACE}/bin/bazel" version